
SELECT STUDENT.ID, STUDENT.NAME, AVG(MARK.GRADE) AS STUDENT_GRADE
FROM (
         SELECT *
         FROM STUDENT
                  INNER JOIN MARK ON STUDENT.ID = MARK.STUDENT_ID
     )

GROUP BY STUDENT.ID HAVING STUDENT_GRADE > 3
